# Generated by Django 3.1.2 on 2020-10-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
