# Generated by Django 3.1.2 on 2020-10-01 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 10, 17, 25, 385016, tzinfo=utc)),
        ),
    ]
