# Generated by Django 3.1.2 on 2020-10-01 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_auto_20201001_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='issued_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 10, 23, 11, 582175, tzinfo=utc)),
        ),
    ]
