# Generated by Django 3.1.2 on 2020-10-01 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_auto_20201001_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='change_collected',
        ),
        migrations.AlterField(
            model_name='product',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 12, 27, 26, 147986, tzinfo=utc)),
        ),
    ]
