# Generated by Django 3.1.2 on 2020-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_auto_20201001_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
