# Generated by Django 3.1.2 on 2020-10-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_product_issue_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='issue_quantity',
            new_name='issued_quantity',
        ),
    ]
