# Generated by Django 3.0.8 on 2020-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_product_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
