# Generated by Django 3.1.2 on 2020-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_sale_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='issued_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
