# Generated by Django 3.1.2 on 2020-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_auto_20201002_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
